### ISSUE TITLE
Add ref to Select to allow closing of dropdown

### ISSUE THREAD

**Issue by paul-vd** [geist-org/geist-ui#399]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Select component should have a ref to enable programmatically closing the dropdown.

### Examples

```jsx

const ref = useRef(null)
const handler = val => {
  console.log(val)
  if(val === "3") ref.current.blur()
}
return (
  <Select ref={ref} placeholder="Choose one" onChange={handler} multiple>
     <Select.Option value="1">Option 1</Select.Option>
     <Select.Option value="2">Option 2</Select.Option>
     <Select.Option value="3">Option 3 should close select</Select.Option>
  </Select>
)

```

**Comment by gepd** [comment]
I'm looking for this as well, I want to use the Select with  `react-hook-form` but I can't at this moment, are you working at this? I saw the code and seems like you need a well understanding of the code to add the `ref` prop

**Comment by unix** [comment]
In fact, `blur` is not controlled by `ref`, because it is not a native `input`, but a component that mimics the behavior of `select`. For this type of component, exporting `ref` is not helpful.

I think you probably don't know how to use `Select` in combination with `react-hook-form`, the `ref` you mentioned is how the [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html) are combined with `react-hook-form`, Geist Select is typically a [controlled component](https://reactjs.org/docs/forms.html#controlled-components), however. It may be helpful to read the documentation at the link.

(If anyone would like to create an online example to illustrate this point it would be very useful)

**Comment by eladg** [comment]
I have the same issue at the moment. It might be a bug a well with `useClickAway`.

My issue is that `useClickAway()` works well, except when you click on a different select dropdown. In that case, both dropdowns are open, while I want the first to close and the second to open.

Now, without a ref, It's not even possible to `setVisible(false)` programmatically as I can not reach the inner element.

@unix IMO, adding a ref would be great, let me know your thoughts and if you want to consider a PR.

**Comment by unix** [comment]
@eladg 
Well, I agreed with you. For controlling between multiple selects, ref is indeed very useful. 

To export `ref` in a mock native component, we must have a set of mock `ref` export functions to match multiple scenario. I'll try to add this feature in the next canary version.

**Comment by eladg** [comment]
Thanks @unix, let me know if there is any way I can help!
