### ISSUE TITLE
Button wave effect not working on edge-rendered Flareact

### ISSUE THREAD

**Issue by 0xAsteria** [geist-org/geist-ui#627]
# Bug report 🐞

## Version & Environment

  - Safari 15.0, Firefox Dev 93.0b3, Brave Nightly 1.31.30 (nightly (arm64))
  - Geist React ^2.2.0

## Expected Behaviour

Buttons should display wave effect when clicked and return to original state.

## Actual results (or Errors)

Button wave effect doesn't happen (across all browsers) and it keeps the same darker border in production. Weirdly, it works as expected in Firefox when running locally (with `yarn dev`).

You can see the issue happening at [zion.land](https://zion.land)

UI code available [here](https://github.com/syvita/zion/tree/main/packages/ui).

**Comment by unix** [comment]
I cloned your repo and ran it with the latest version of `@gesit-ui/core` and it did reproduce the issue:
- The reason the style is not applied is that the JavaScript is not working as expected, including some pre-processed code.
- Any component that requires JavaScript will not run.
- If the [_app.js#L6](https://github.com/syvita/zion/blob/mainnet/packages/ui/pages/_app.js#L6) statement is commented out, JavaScript will run.

After debugging, I think this is a problem caused by `webpack` in Flareact's handling of Geist when packaging. Component `CssBaseline` is not packaged as expected and blocks the rest of the code, even if you add any code to `index.js`. After testing I can confirm the following points:

- Geist works with `webpack` and works fine after bundle.
- Geist works with `esbuild` and works fine after bundle.
- Geist works with `rollup` and works fine after bundle.
- Geist works with `next.js` and works fine after bundle.

I suspect that customizing the `webpack` configuration within the `wip.flareact.config.js` file would solve this issue. However, there are too few documents of Flareact, and I don't know its packaging scheme, so, this issue remains unresolved.

**Comment by unix** [comment]
This issue was closed because it was not active for a long time, please reopen when there are updates.
